# Input
input_directory: example_data/raw_reads
variants_file: example_data/variants.txt

# output
output_directory: example_output

# barcode detection
reverse_complement_output: True # return reverse complement of the barcode
flanks: "CCTGGGCTGG...TGGGCCTCTC"   # needs to match the read orientation

barcode_length_min: 21
barcode_length_max: 21
error_rate: 0.1                # error rate for flanking region detection; the number of allowed errors are rounded by cutadapt, meaning it not allow errors for short flanking regions even though the error rate is not 0; info in the created cutadapt log
cutadapt_cores: 0               # when 0, cutadapt automatically detects the maximum number of cores. Careful when setting in conjunction with snakemake --cores >1
